Repository peaqnetwork/peaq-network-ev-charging-sim-be, pull requests merged in 2022-05, with the labels that each got.

#45 Add try catch to retry if the broken pipe happens
  src/bs_logic.py
  src/chain_utils.py
  test/test_chain_utils.py
  tool/user_behavior_simulation.py
  tool/utils.py
Labels: size/L, approved

#47 Fix/1202209979674237 updated deyploment kind to statefulset
  charts/peaq-network-ev-charging-sim-be/templates/statefulset.yaml
  charts/peaq-network-ev-charging-sim-be/values.yaml
Labels: size/M, approved, lgtm

#48 hotfix: pod creation failed
  charts/peaq-network-ev-charging-sim-be/values.yaml
Labels: size/XS, approved

#49 hotfix: shorten override name
  charts/peaq-network-ev-charging-sim-be/templates/_helpers.tpl
  charts/peaq-network-ev-charging-sim-be/values.yaml
Labels: size/XS, approved

#50 hotfix: update temülate fullname
  charts/peaq-network-ev-charging-sim-be/templates/_helpers.tpl
Labels: size/XS, approved

#52 fix: add overridename
  charts/peaq-network-ev-charging-sim-be/templates/canary.yaml
  charts/peaq-network-ev-charging-sim-be/templates/hpa.yaml
  charts/peaq-network-ev-charging-sim-be/templates/ksvc.yaml
  charts/peaq-network-ev-charging-sim-be/templates/sa.yaml
  charts/peaq-network-ev-charging-sim-be/templates/service.yaml
  charts/peaq-network-ev-charging-sim-be/templates/statefulset.yaml
  charts/peaq-network-ev-charging-sim-be/values.yaml
Labels: size/M, approved

#54 add: staging pipeline
  .lighthouse/jenkins-x/staging.yaml
  .lighthouse/jenkins-x/triggers.yaml
  OWNERS
Labels: size/M
