Repository peaqnetwork/peaq-network-ev-charging-sim-be, pull requests merged in 2022-04, with the labels that each got.

#38 Feat/enable secret env
  charts/peaq-network-ev-charging-sim-be/templates/deployment.yaml
  charts/peaq-network-ev-charging-sim-be/values.yaml
Labels: size/M, approved

#33 Feat/1202107321878171 hide mnemonic
  be.py
  etc/config.yaml
  etc/did_doc.json
  src/bs_logic.py
  src/config_utils.py
  tool/consumer.config.yaml
  tool/sudo.config.yaml
  tool/user_behavior_simulation.py
Labels: size/M

#39 Check env
  .gitignore
  .lighthouse/jenkins-x/triggers.yaml
  OWNERS
  src/config_utils.py
Labels: size/S

#41 Update readme
  README.md
Labels: approved

#42 update: read me
  README.md
Labels: size/XS, approved

#43 Remove the non-exist variable
  src/bs_logic.py
Labels: size/XS, approved

#44 Bug/1202189506746355 broken pipe more log
  src/bs_logic.py
Labels: size/XS, approved
